### ISSUE TITLE
There's a problem with the cursor (drag)

### ISSUE THREAD

**Issue by notbadgun** [britzl/defold-input#10]
If you click on the object and quickly move it (drag), it will be moved with an offset. As a result, in dynamic game, the player does not have enough objects and drags them accurately, but with offsets(((

Can this be fixed?
Thanks!

This GIF is recorded in your demo.
GIF: https://imgur.com/sj8u2Ap

**Comment by britzl** [comment]
Well, if the click and large movement happens in the same frame this will unfortunately happen. I'm not really sure how to solve it.

**Comment by britzl** [comment]
Some changes have been made to the cursor script since this bug was reported. And regardless, it's likely difficult to fix completely anyway. Closing.
