### ISSUE TITLE
No description about input_bindings in README 

### ISSUE THREAD

**Issue by wsjscss** [britzl/defold-input#13]
I spent about 1 hour to detect why I can't get the `message_id == cursor.CLICKED`
The reason was - different `game.input_bindings ` configuration.
In my project I set `Mouse trigger -> Button 1: click` and it break `cursor.CLICKED` message with no warnings or any help to detect what error. After changing `Mouse trigger -> Button 1: touch` - everything works. 

I suggest to add some instructions how to configure `game.input_bindings`, or add some warnings in library core like "You have no touch events in input config file. CLICK events won't wok"

Thank you =)

**Comment by britzl** [comment]
I added an extra note about this in the readme for the cursor script:

https://github.com/britzl/defold-input/blob/master/in/cursor.md

There was already documentation about the `action_id` script property.
