### ISSUE TITLE
Gestures doesn't have default value for multitouch 

### ISSUE THREAD

**Issue by Apetzu** [britzl/defold-input#14]
According to [gesture.md](https://github.com/britzl/defold-input/blob/master/in/gesture.md#configuration), multi_touch setting should be true but it doesn't exist in [gesture.lua](https://github.com/britzl/defold-input/blob/master/in/gesture.lua#L5).

I figured out this while I was trying to do pinch gesture detection and it didn't work until I set multi_touch to true. Maybe accidentally left off?

**Comment by britzl** [comment]
Thanks for pointing this out!
