### ISSUE TITLE
Cursor registering click at multiple places

### ISSUE THREAD

**Issue by mikson60** [britzl/defold-input#15]
Hello,

I am having an issue where the cursor seems to be registering a click on multiple entities at the same time while the cursor is hovered only on top of another.

This happens more often when there are many sprites on the screen. A certain case: 1. the sprite I click on is in the middle of the screen; 2. the click is registered on that sprite and another sprite at the edge of the screen. 

This usually seems to happen in a way that the faulty register happens at the edge of the screens.

What can I do about this?

**Comment by britzl** [comment]
Can you please share an example project where this happens?

**Comment by britzl** [comment]
Fixed in release: https://github.com/britzl/defold-input/releases/tag/2.8.5
