### ISSUE TITLE
Green aliens can't be dragged in cursor_and_camera example

### ISSUE THREAD

**Issue by dri-richard** [britzl/defold-input#17]
In the cursor_and_camera example, cursor movement is always captured by the camera drag, so that dragging green aliens is no longer possible.

**Comment by dri-richard** [comment]
The problem is reproducible in editor builds, but the HTML example seems to be working as expected

**Comment by britzl** [comment]
Thank you for reporting! The problem was that it was possible to drag the camera even if the cursor was over something
