### ISSUE TITLE
Bindings and gamepads

### ISSUE THREAD

**Issue by brettmjohnson** [britzl/defold-input#18]
I noticed the "all.input_binding" matches the Defold builtins, and the "default.gamepads" in builtins has way more profiles than "in.gamepads". Should I be using the builtins in both cases?

**Comment by subsoap** [comment]
Things changed over time. Probably the version in this repo are older than the now updated builtins but still may have some useful things. You'll need to decide what's right for your project / suggest changes to the repo based on the differences you see.

**Comment by brettmjohnson** [comment]
I confirmed "all.input_binding" is the same.

The builtin "default.gamepads" file contains all the devices from "in.gamepads" except "Generic   USB  Joystick  ". Also, some of the maps differ on "Wireless Controller" for osx.

That said, I'm going to use the builtins since there's only upsides there. I'd suggest maybe removing those files from the repo for simplicity. To avoid breaking others' projects, maybe updating the files to match the builtins would be better and changing the example project to use the builtins so people avoid this situation in the future?

Anyway, it's a handy tool.

**Comment by britzl** [comment]
@brettmjohnson good suggestion. The files are indeed old and I forgot they even existed in the repo!

**Comment by britzl** [comment]
I decided to remove them and make a new major version release.
