### ISSUE TITLE
Request: Distance from origin on drag

### ISSUE THREAD

**Issue by Trevortni** [britzl/defold-input#21]
I suppose this is my fault that I didn't realize this earlier, but I'm pretty sure dx and dy only give the distance traveled since the last frame. Would it be possible to get a pair of extra values representing the distance from where the mouse button was first pressed?

For that matter, just knowing where the mousedown first occurred could be useful as well, though I only really need one or the other at the moment (since having one gives you the other via math).

**Comment by britzl** [comment]
You should get a drag start event I think. And it should contain a starting position.

**Comment by Trevortni** [comment]
> You should get a drag start event I think. And it should contain a starting position.

This is in the drag start event. Well, it's in the listener for the drag start event, anyway. If there's a starting position there, I don't see it.

![image](https://user-images.githubusercontent.com/5759498/121796738-3a7f7600-cbd0-11eb-9a59-c357417038ac.png)

**Comment by britzl** [comment]
Isn't the x & y values the starting position?

**Comment by Trevortni** [comment]
Here's dragging the same object from the same starting point the opposite direction:

![image](https://user-images.githubusercontent.com/5759498/121796826-c72a3400-cbd0-11eb-9035-acf37d20ea7f.png)

**Comment by Trevortni** [comment]
I'm pretty sure x and y are the current cursor position.

**Comment by britzl** [comment]
Ah, true, it is not the same as the initial pressed position, but rather the position when the drag started (ie when moving the cursor above the drag threshold).
