### ISSUE TITLE
OnScreen: Changing analog stick position to where a user touches

### ISSUE THREAD

**Issue by ProgrammingLife** [britzl/defold-input#37]
What's the simpliest way to change analog position to a place where a user just touched?

**Comment by britzl** [comment]
I recommend that you start from this example:

https://github.com/britzl/defold-input/blob/master/examples/onscreen_gui/controls.gui_script

And then modify `on_input` so that you move the analog stick if the input wasn't handled and then call `onscreen.on_input()` again.
