### ISSUE TITLE
Defect in multitouch handling on iOS devices

### ISSUE THREAD

**Issue by lharder** [britzl/defold-input#38]
There seems to be a new problem with multitouch handling of input events when using the onscreen controls. Virtual stick movement and button touches do not seem to be handled in parallel anymore with the latest version, as can be seen in the onscreen example:

On iOS devices (tested on an iPhone 14, iOS version 16.7 20H19), with the current version input library 4.6.1. master branch, the spaceship can either move or shoot - but not both at the same time. I checked the older version 4.5.1. and with that version, the behavior is still as expected, movement and shooting works in parallel.

**Comment by ufgo** [comment]
Same problem on the android device Redmi Note 12 PRO

**Comment by britzl** [comment]
Ah, sorry about that. It has been fixed now!
