### ISSUE TITLE
cursor.OVER reporting game object under (lower z) the tompost game object

### ISSUE THREAD

**Issue by BSDGuyShawn** [britzl/defold-input#42]
The cursor.OVER message is reporting game objects stacked below the topmost game object.

When moving the cursor up on the screen over stacked game objects it is issuing cursor.OUT messages for the topmost game object followed by cursor.OVER messages for the underlying game object. It does this for all the objects in the stack as can be seen in the attached video.

When moving the cursor down on the screen I see what I would call expected behavior. it doesn't issue cursor.OUT / cursor.OVER messages until the cursor has moved over the object and seems to ignore game objects lower in the stack.

https://github.com/britzl/defold-input/assets/1402771/fcfa9d2b-deaa-48f8-a438-5c4dc27c9e32

If you need additional information or would like me to try something, please let me know.

**Comment by britzl** [comment]
> If you need additional information or would like me to try something, please let me know.

I'm not able to reproduce the problem. Could you please share a small project where I can test this?

**Comment by BSDGuyShawn** [comment]
> I'm not able to reproduce the problem. Could you please share a small project where I can test this?

I will work on putting this together this evening.

**Comment by BSDGuyShawn** [comment]
In setting up the sample project I found that my issue was being caused by the separation of the items on the Z axis and the thickness of the collider.

My project was using the DEFAULT_NEAR = -1 /DEFAULT_FAR = 1 of the default renderer. My objects were only .0001 apart on the Z axis.

Sorry for the false alarm and taking your time.
