### ISSUE TITLE
 Combine the cursor module and the gesture module

### ISSUE THREAD

**Issue by DonsWayo** [britzl/defold-input#7]
Please, can you provide an  example combine this two modules?
Thanks.

**Comment by britzl** [comment]
Added an example of how to combine cursor and gesture modules:

CODE: https://github.com/britzl/defold-input/tree/master/examples/cursor_and_gesture
HTML5: https://britzl.github.io/Defold-Input/

**Comment by DonsWayo** [comment]
thanks for the demo, works perfect!, only one question. I try to modify the gesture.lua to get the value of long press and swipe direction without the release (on pressed get directly the value), is this posible?

Thanks for the effort.

**Comment by britzl** [comment]
I've added drag detection in this branch: https://github.com/britzl/defold-input/tree/drag_gesture
