### ISSUE TITLE
cursor.script doesn't really send messages to game objects.

### ISSUE THREAD

**Issue by theoybema** [britzl/defold-input#8]
Hi,

I found an issue with the cursor script. It didn't seem to send any messages to my game objects. I think the problem is here:
local function notify_event(self, game_object_id, game_object_group, action, message_id)
	-- pcall to check if the game object exists since it might have been deleted
	-- typically a cursor_out message that is generated when the game object is deleted
	local exists,_ = pcall(function()
		go.get_id(game_object_id)
	end)
Your error catching doesn't function, _because go.get_id_ expects a URL and _game_object_id_ is a hash. It always throws an error, and not because the game object doesn't exists.
I changed the function in go.get_position(game_object_id) because that function does expect a hash and then it seems to work.

I'm new to GitHub, so have patience with me. I haven't figured out pull requests yet.

best,
Theo Ybema

**Comment by britzl** [comment]
Thank you! I've pushed a new version with a fix
